MyKbb.Master/src/MyKbb.Master/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyKbb.Master.Models
{
    public enum BodyStyle
    {
        Coupe,
        Van,
        Truck
    }

    public enum TransmissionStyle
    {
        Manual,
        Automatic
    }
    public enum EngineType
    {
        V6,
        V8
    }
    public class Car
    {
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public int Year { get; set; }
        public string Model { get; set; }
        public BodyStyle Body { get; set; }
        public string ExteriorColor { get; set; }
        public TransmissionStyle Transmission { get; set; }
        public EngineType Engine { get; set; }
        public string ThumbNail { get; set; }
        public string Price { get; set; }
        public string SpecialProperty { get; set; }
    }
}

MyKbb.Master/src/MyKbb.Master/Models/InventoryViewModel.cs
using MyKbb.Master.DataAccess.Models;
using System.Collections.Generic;

namespace MyKbb.Master.Models
{
    public class InventoryViewModel
    {
        public IList<Car> Cars { get; set; }
        public PaginationViewModel Page { get; set; }
        public IEnumerable<KeyValuePair<string,string>> manufacturerFacet { get; set; }
        public IEnumerable<KeyValuePair<string, string>> YearFacet { get; set; }
    }
}

MyKbb.Master/src/MyKbb.Master/Models/KbbContext.cs
using Microsoft.Data.Entity;

namespace MyKbb.Master.Models
{
    public class KbbContext: DbContext
    {
        public DbSet<Car> Cars { get; set; }
    }
}

MyKbb.Master/src/MyKbb.Master/Models/PaginationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyKbb.Master.Models
{
    public class PaginationViewModel
    {
        public int TotalPageCount { get; set; }
        public int CurrentPageId { get; set; }
        public string PageUrl { get; set; }
    }
}

MyKbb.Master/src/MyKbb.Master/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using MyKbb.Master.DataAccess;

namespace MyKbb.Master.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

MyKbb.Master/src/MyKbb.Master/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using MyKbb.Master.DataAccess;
using MyKbb.Master.Services;
using MyKbb.Master.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MyKbb.Master.Controllers
{
    public class InventoryController : Controller
    {
        private IInventoryService _inventoryService;
        private const int pageSize = 2;
        public InventoryController(IInventoryService inventoryService)
        {
            _inventoryService = inventoryService;
        }
        // GET: /<controller>/
        public IActionResult Index(string pageId, string manufacturer,string years)
        {
            var viewModel = BuildViewModel(pageId, manufacturer, years);
            return View(viewModel);
        }

        private object BuildViewModel(string pageId, string manufacturer, string years)
        {
            var viewModel = new InventoryViewModel();
            
            var filteredCars = _inventoryService.GetCars(manufacturer, years);
            //build pagination model
            viewModel.Page = GetPageModel(pageId, filteredCars.Count, manufacturer, years);

            //take current page rows from filtered cars list
            //better if paging is done while querying data, but tradeoff is you need to query DB second time
            //to get details for filters
            viewModel.Cars = filteredCars.Skip(viewModel.Page.CurrentPageId * pageSize).Take(pageSize).ToList();
            
            //get distinct manufacturers and their count for current resultset
            viewModel.manufacturerFacet = filteredCars.GroupBy((item => item.manufacturer),
             (key, elements) => new KeyValuePair<string,string>(key, elements.Distinct().Count().ToString()));
            
            //get distinct years and their count for current resultset
            viewModel.YearFacet = filteredCars.GroupBy((item => item.Year),
                         (key, elements) => new KeyValuePair<string, string>(key.ToString(), elements.Distinct().Count().ToString()));

            return viewModel;
        }

        private PaginationViewModel GetPageModel(string pageId, int totalCarCount, string manufacturer, string years)
        {
            var pageModel = new PaginationViewModel();
            pageModel.PageUrl = "~/inventory/" + 
                ((!string.IsNullOrEmpty(manufacturer) || !string.IsNullOrEmpty(years)) ? "?manufacturer=" + manufacturer + "&years=" + years : "");
            pageModel.TotalPageCount = totalCarCount / pageSize;
            pageModel.CurrentPageId = string.IsNullOrEmpty(pageId) ? 0 : Convert.ToInt16(pageId);

            return pageModel;
        }
    }
}

MyKbb.Master/src/MyKbb.Master/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

MyKbb.Master/src/MyKbb.Master/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyKbb.Master/src/MyKbb.Master/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/ASP-NET-Banners-01.png" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-02-VS.png" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/ASP-NET-Banners-02.png" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Banner-01-Azure.png" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET MVC 6</li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518007">Gulp</a> and <a href="http://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="http://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699314">Add an appsetting in config and access it in app.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET 5</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET 5 such as Startup and middleware.</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517852">Run your app on .NET Core</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=517853">Run commands in your project.json</a></li>
            <li><a href="http://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MyKbb.Master/src/MyKbb.Master/Views/Inventory/DisplayTemplates/Car.cshtml
@model MyKbb.Master.DataAccess.Models.Car

<div class="panel panel-default">
    <div class="panel-body row" style="background-color:#f5f5f5;">
        <div class="col-md-2 text-center">
            <p>$ @Model.Price</p>
        </div>
        <div class="col-md-3">
            <img src="~/uploads/@Model.ThumbNail" height="150" width="150" />
        </div>
        <div class="col-md-7">
            <div><h3>@Model.Model</h3></div>
            <br />
            <div class="row">
                <div class="col-md-5">
                    <div><b>manufacturer</b> @Model.manufacturer</div>
                    <div><b>Transmission</b> @Model.Transmission</div>
                </div>
                <div class="col-md-3">
                    <div><b>Body</b> @Model.Body</div>
                    <div><b>Engine</b> @Model.Engine</div>
                </div>
                <div class="col-md-4">
                    <div><b>Ext.Color</b> @Model.ExteriorColor</div>
                    <div><b>Year</b> @Model.Year</div>
                </div>
            </div>
            <div class="row">
                <p>
                    @if (Model.Body == MyKbb.Master.DataAccess.Models.BodyStyle.Truck)
                    {

                    }
                    @if (Model.Body == MyKbb.Master.DataAccess.Models.BodyStyle.Van)
                    {
                        /**/
                    }
                </p>

            </div>
        </div>
    </div>
</div>

MyKbb.Master/src/MyKbb.Master/Views/Inventory/Index.cshtml
@model MyKbb.Master.Models.InventoryViewModel

@{
    ViewData["Title"] = "Cars Inventory";
}
<div class="row">
    <div class="col-md-3">
        <h2>Cars Inventory</h2>
    </div>
    <div class="col-md-8">
        @Html.DisplayFor(m => m.Page)
    </div>
    <div class="col-md-1">
    </div>
</div>

<div class="container">
    <div class="col-md-2" style="margin-right: 5px;">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Manufacturer
                </div>
                <div class="panel-body">
                    @foreach (var item in Model.manufacturerFacet)
                    {
                        <input type="checkbox" class="manu"  id="@item.Key" value="@item.Key"> @(String.Format("{0} ({1})", item.Key, item.Value)) <br> 
                    }
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    Year
                </div>
                <div class="panel-body">
                    @foreach (var item in Model.YearFacet)
                    {
                        <input type="checkbox" class="year" id="@item.Key" name="@item.Key"> @(String.Format("{0} ({1})", item.Key, item.Value)) <br>
                    }
                </div>
            </div>
            <div>
                <input type="button" id="applyFilter" value="Apply Filter" />
                <a href="javascript:void(0);" id="clearFilter">Clear</a>
            </div>

        </div>
    </div>
    <div class="col-md-9">
        <div class="col-md-12">
            @Html.DisplayFor(m => m.Cars)
        </div>
    </div>
</div>

@section scripts {
<script type="text/javascript">
    $("#clearFilter").click(function () {
        $(".manu:checked").prop('checked', false);
        $(".year:checked").prop('checked', false);

    });
    $("#applyFilter").click(function () {
        if ($('.manu:checked').length || $('.year:checked').length) {
            var manufacturers ='',
                years ='';
            $('.manu:checked').each(function () {
                manufacturers += ","+ this.id;
            });
            $('.year:checked').each(function () {
                years += "," + this.id;
            });
            manufacturers = manufacturers.slice(1);
            years = years.slice(1);
            window.location.href = '/inventory/?manufacturer=' + manufacturers + '&years=' + years;
        } else {
            alert("Please select at least one filter to proceed.");
        }

    })
</script>
}

MyKbb.Master/src/MyKbb.Master/Views/Shared/DisplayTemplates/PaginationViewModel.cshtml
@model MyKbb.Master.Models.PaginationViewModel
@{ 
    var urlStr = Model.PageUrl + ( Model.PageUrl.Contains('?') ? "&" : "?") + "pageId=";
}
<div class="pull-right pagination">
    <ul class="pagination">
        <li class="page-pre"><a href="@urlStr@( Model.CurrentPageId > 0 ? Model.CurrentPageId - 1 : 0 )">‹</a></li>
        @for (int i = 0; i < Model.TotalPageCount; i++)
        {
            if (Model.CurrentPageId == i)
            {
                <li class="page-number active"><a href="@urlStr@i">@(i + 1)</a></li>
            }
            else
            {
                <li class="page-number"><a href="@urlStr@i">@(i + 1)</a></li>
            }
        }
        <li class="page-next"><a href="@urlStr@( Model.CurrentPageId <Model.TotalPageCount -1 ? Model.CurrentPageId +1 : Model.TotalPageCount - 1 )">›</a></li>
    </ul>
</div>

MyKbb.Master/src/MyKbb.Master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyKbb.Master</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">MyKbb.Master</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Inventory" asp-action="Index">Inventory</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - MyKbb.Master</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>